apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloud-web-app
  description: Cloud web application with Docker build pipeline
  annotations:
    github.com/project-slug: Akash-sunagar/cloud-web-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: devops-team
  lifecycle: production
