apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  description: Backend service for managing akash&varun&rohit&users
  annotations:
    github.com/project-slug: Akash-sunagar/user-service
    backstage.io/techdocs-ref: "dir:."
spec:
  type: service
  owner: devops-team
  lifecycle: development
  providesApis:
    - api:user-api